[Server]
    Host = "localhost"
    Port = "1112"
    JWTSecret = "zK-PbX9idyU"

[RDB]
    Driver = "postgres"
    User = "pelletier"
    Password = "mypassword"

[Logger]
  Development = false
  Level = "info"
  Encoding = "json"
  OutputPaths = ["stdout"]
  AppErrorOutputPaths = ["stderr", "./err.log"]
  ErrorOutputPaths = ["stderr"]
  [Logger.EncoderConfig]
    MessageKey = "msg"
    LevelKey = "lvl"
    TimeKey = "ts"
    NameKey = "name"
    CallerKey = "caller"
    StacktraceKey = "stacktrace"
    LevelEncoder = ""
    CallerEncoder = "short"

    